/**
 * Builds a polished, self-contained HTML document for a single job's grading
 * result — used for both "Export as HTML" and "Export as PDF".
 */

import { getBand, type BandKey } from "@/lib/grading/bands";
import { gradeColor } from "@/lib/grade-colors";
import type { Evaluation, Family, Job, Org } from "@/types";

const esc = (s: unknown) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

interface BreakdownRow {
  name?: string;
  levelLabel?: string;
  levelIndex?: number;
  score?: number;
}

export function buildJobDocument(opts: {
  job: Job;
  evaluation?: Evaluation;
  org?: Org;
  family?: Family;
}): { title: string; html: string; body: string } {
  const { job, evaluation, org, family } = opts;
  const grade = job.currentGrade ?? null;
  const gc = grade != null ? gradeColor(grade) : null;
  const band = getBand(job.band as BandKey);
  const breakdown = (evaluation?.breakdown ?? []) as BreakdownRow[];
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const factorRows = breakdown
    .map(
      (b, i) => `
      <tr>
        <td class="f">${esc(b.name)}</td>
        <td class="lv">${b.levelIndex != null && b.levelIndex >= 0 ? `L${b.levelIndex + 1}` : "—"}</td>
        <td>${esc(b.levelLabel)}</td>
        <td class="num">${esc(b.score)}</td>
      </tr>`,
    )
    .join("");

  const flags = (evaluation?.flags ?? job.flags ?? []) as string[];
  const flagsHtml = flags.length
    ? `<div class="flags"><h3>Review flags</h3><ul>${flags.map((f) => `<li>${esc(f)}</li>`).join("")}</ul></div>`
    : "";

  const jdHtml = job.jd
    ? `<div class="section"><h2>Job description</h2><div class="jd">${esc(job.jd).replace(/\n/g, "<br/>")}</div></div>`
    : "";

  const body = `
  <div class="doc">
    <div class="head">
      <div>
        <div class="org">${esc(org?.name ?? "Gradex")}</div>
        <h1>${esc(job.title)}</h1>
        <div class="sub">${esc(band.code)} · ${esc(band.name)} &nbsp;•&nbsp; ${job.careerPath === "M" ? "Management" : "Individual Contributor"}${family ? ` &nbsp;•&nbsp; ${esc(family.name)}` : ""}</div>
      </div>
      <div class="gradebox" style="background:${gc?.solid ?? "#e5e7eb"};color:${gc?.foreground ?? "#111"}">
        <div class="gl">Grade</div>
        <div class="gv">${grade ?? "—"}</div>
      </div>
    </div>

    <div class="meta">
      ${family ? `<div><span>Department</span><b>${esc(family.name)}</b></div>` : ""}
      ${job.section ? `<div><span>Section</span><b>${esc(job.section)}</b></div>` : ""}
      ${job.division ? `<div><span>Division</span><b>${esc(job.division)}</b></div>` : ""}
      ${job.unit ? `<div><span>Unit</span><b>${esc(job.unit)}</b></div>` : ""}
      <div><span>Status</span><b>${esc(job.status)}</b></div>
      <div><span>Confidence</span><b>${esc(job.confidence ?? "—")}</b></div>
      <div><span>Band window</span><b>${evaluation?.bandWindow ? `${evaluation.bandWindow.lo}–${evaluation.bandWindow.hi}` : "—"}</b></div>
      <div><span>Raw score</span><b>${evaluation ? `${evaluation.rawScore} / ${evaluation.rMax}` : "—"}</b></div>
      ${org?.scoping?.completed ? `<div><span>Company grade</span><b>${org.scoping.result.companyGrade}</b></div>` : ""}
    </div>

    ${job.jobPurpose ? `<div class="section"><h2>Job purpose</h2><p>${esc(job.jobPurpose)}</p></div>` : ""}

    <div class="section">
      <h2>GGS factor evaluation</h2>
      <table class="factors">
        <thead><tr><th>Factor</th><th>Level</th><th>Selected definition</th><th class="num">Pts</th></tr></thead>
        <tbody>${factorRows || `<tr><td colspan="4" class="muted">Not graded yet.</td></tr>`}</tbody>
      </table>
      ${flagsHtml}
    </div>

    ${jdHtml}

    <div class="foot">Generated by Gradex on ${date} · An independent platform inspired by the Global Grading System.</div>
  </div>`;

  const css = `
    * { box-sizing: border-box; }
    body { margin:0; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color:#0f1129; background:#fff; }
    .doc { max-width: 800px; margin: 0 auto; padding: 40px; }
    .head { display:flex; justify-content:space-between; align-items:flex-start; gap:24px; border-bottom:2px solid #eef0f6; padding-bottom:20px; }
    .org { font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; color:#6E56CF; }
    h1 { margin:6px 0 4px; font-size:26px; letter-spacing:-.02em; }
    .sub { color:#6b6f8a; font-size:13px; }
    .gradebox { border-radius:14px; padding:14px 20px; text-align:center; min-width:96px; box-shadow:0 6px 18px rgba(0,0,0,.12); }
    .gl { font-size:11px; text-transform:uppercase; letter-spacing:.08em; opacity:.85; }
    .gv { font-size:40px; font-weight:800; line-height:1; }
    .meta { display:flex; flex-wrap:wrap; gap:10px; margin:20px 0; }
    .meta > div { flex:1; min-width:120px; background:#f7f8fc; border:1px solid #eef0f6; border-radius:10px; padding:10px 12px; }
    .meta span { display:block; font-size:11px; color:#6b6f8a; text-transform:uppercase; letter-spacing:.05em; }
    .meta b { font-size:15px; text-transform:capitalize; }
    .section { margin-top:24px; }
    h2 { font-size:15px; margin:0 0 10px; padding-bottom:6px; border-bottom:1px solid #eef0f6; }
    .section p { font-size:14px; line-height:1.6; color:#2a2c45; margin:0; }
    table.factors { width:100%; border-collapse:collapse; font-size:13px; }
    table.factors th { text-align:left; background:#f2f3f8; color:#6b6f8a; font-size:11px; text-transform:uppercase; letter-spacing:.04em; padding:8px 10px; }
    table.factors td { padding:9px 10px; border-bottom:1px solid #eef0f6; }
    table.factors td.f { font-weight:600; width:30%; }
    table.factors td.lv { color:#6E56CF; font-weight:700; width:8%; }
    .num { text-align:right; font-variant-numeric: tabular-nums; }
    .muted { color:#9ea2bb; text-align:center; }
    .flags { margin-top:14px; background:#fff7ed; border:1px solid #fed7aa; border-radius:10px; padding:10px 14px; }
    .flags h3 { margin:0 0 6px; font-size:13px; color:#b45309; }
    .flags ul { margin:0; padding-left:18px; font-size:13px; color:#7c4a13; }
    .jd { font-size:13px; line-height:1.65; color:#2a2c45; }
    .foot { margin-top:32px; padding-top:14px; border-top:1px solid #eef0f6; font-size:11px; color:#9ea2bb; text-align:center; }
  `;

  const title = `${job.title} — Grade ${grade ?? ""}`.trim();
  const html = `<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title><style>${css}</style></head><body>${body}</body></html>`;
  return { title, html, body: `<style>${css}</style>${body}` };
}
