/**
 * Builds a polished, self-contained HTML report for the workforce pay analysis.
 */

import type { PayAnalysis } from "@/lib/pay/analytics";

const esc = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function buildPayAnalysisDocument(a: PayAnalysis, currency: string, orgName: string): { html: string; filename: string } {
  const money = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(v || 0);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const bars = (items: { label: string; value: number }[], color: string) => {
    const max = Math.max(1, ...items.map((i) => i.value));
    return `<div class="bars">${items
      .map(
        (i) =>
          `<div class="bar-row"><span class="bl">${esc(i.label)}</span><span class="bt"><span class="bf" style="width:${(i.value / max) * 100}%;background:${color}"></span></span><span class="bv">${i.value}</span></div>`,
      )
      .join("")}</div>`;
  };

  const kpi = (label: string, value: string, sub = "") =>
    `<div class="kpi"><div class="kl">${esc(label)}</div><div class="kv">${esc(value)}</div>${sub ? `<div class="ks">${esc(sub)}</div>` : ""}</div>`;

  const gradeRows = a.byGrade
    .map(
      (g) =>
        `<tr><td>G${g.grade}</td><td class="n">${g.count}</td><td class="n">${money(g.avgSalary)}</td><td class="n">${money(g.median)}</td><td class="n">${Math.round(g.avgCompa * 100)}%</td></tr>`,
    )
    .join("");

  const deptRows = a.byDepartment
    .map((d) => `<tr><td>${esc(d.label)}</td><td class="n">${d.count}</td><td class="n">${money(d.avgSalary)}</td></tr>`)
    .join("");

  const genderRows = a.byGender
    .map((g) => `<tr><td>${esc(g.label)}</td><td class="n">${g.count}</td><td class="n">${money(g.avgSalary)}</td></tr>`)
    .join("");

  const body = `
  <div class="doc">
    <div class="head">
      <div>
        <div class="org">${esc(orgName)}</div>
        <h1>Total Rewards — Pay Analysis</h1>
        <div class="sub">Workforce pay vs. current grade structure</div>
      </div>
    </div>

    <div class="kpis">
      ${kpi("Headcount", String(a.headcount), `${a.assigned} matched`)}
      ${kpi("Total cost", money(a.totalCost))}
      ${kpi("Average salary", money(a.avgSalary), `median ${money(a.medianSalary)}`)}
      ${kpi("Avg compa-ratio", `${Math.round(a.avgCompaRatio * 100)}%`)}
      ${kpi("Cost to minimum", money(a.budgetToMin), "remediate underpaid")}
      ${kpi("Cost to midpoint", money(a.budgetToMid))}
      ${kpi("Gender pay gap (mean)", `${a.genderPayGapMean}%`, `median ${a.genderPayGapMedian}%`)}
      ${kpi("Pay competitiveness", `${a.meets} in range`, `${a.underpaid} under · ${a.overpaid} over`)}
    </div>

    <div class="grid2">
      <div class="card"><h2>Compa-ratio distribution</h2>${bars(a.compaDistribution, "#4DABF7")}</div>
      <div class="card"><h2>Range placement (quartiles)</h2>${bars(a.quartileDistribution, "#5B5BF5")}</div>
      <div class="card"><h2>Headcount by tenure</h2>${bars(a.tenureGroups, "#16C098")}</div>
      <div class="card"><h2>Headcount by age</h2>${bars(a.ageGroups, "#F5A524")}</div>
    </div>

    <div class="section"><h2>Pay by grade</h2>
      <table><thead><tr><th>Grade</th><th class="n">Headcount</th><th class="n">Avg salary</th><th class="n">Median</th><th class="n">Avg compa</th></tr></thead><tbody>${gradeRows}</tbody></table>
    </div>

    <div class="grid2">
      <div class="section"><h2>Pay by gender</h2><table><thead><tr><th>Gender</th><th class="n">Headcount</th><th class="n">Avg salary</th></tr></thead><tbody>${genderRows}</tbody></table></div>
      <div class="section"><h2>Headcount by department</h2><table><thead><tr><th>Department</th><th class="n">Headcount</th><th class="n">Avg salary</th></tr></thead><tbody>${deptRows}</tbody></table></div>
    </div>

    <div class="foot">Generated by Gradex on ${date} · Total Rewards analytics.</div>
  </div>`;

  const css = `
    *{box-sizing:border-box}
    body{margin:0;font-family:'Segoe UI',system-ui,-apple-system,sans-serif;color:#0f1129;background:#fff}
    .doc{max-width:900px;margin:0 auto;padding:40px}
    .head{border-bottom:2px solid #eef0f6;padding-bottom:18px;margin-bottom:20px}
    .org{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#5B5BF5}
    h1{margin:6px 0 2px;font-size:24px;letter-spacing:-.02em}
    .sub{color:#6b6f8a;font-size:13px}
    .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:22px}
    .kpi{background:#f7f8fc;border:1px solid #eef0f6;border-radius:12px;padding:12px 14px}
    .kl{font-size:11px;color:#6b6f8a;text-transform:uppercase;letter-spacing:.05em}
    .kv{font-size:20px;font-weight:800;margin-top:2px}
    .ks{font-size:11px;color:#9ea2bb;margin-top:2px}
    .grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:22px}
    .card,.section{border:1px solid #eef0f6;border-radius:12px;padding:14px 16px;margin-bottom:16px}
    h2{font-size:14px;margin:0 0 12px}
    .bars{display:flex;flex-direction:column;gap:8px}
    .bar-row{display:flex;align-items:center;gap:10px;font-size:12px}
    .bl{width:90px;color:#2a2c45}
    .bt{flex:1;height:10px;background:#f2f3f8;border-radius:999px;overflow:hidden}
    .bf{display:block;height:100%;border-radius:999px}
    .bv{width:36px;text-align:right;font-weight:700;font-variant-numeric:tabular-nums}
    table{width:100%;border-collapse:collapse;font-size:13px}
    th{text-align:left;background:#f2f3f8;color:#6b6f8a;font-size:11px;text-transform:uppercase;letter-spacing:.04em;padding:8px 10px}
    td{padding:8px 10px;border-bottom:1px solid #eef0f6}
    .n{text-align:right;font-variant-numeric:tabular-nums}
    .foot{margin-top:28px;padding-top:14px;border-top:1px solid #eef0f6;font-size:11px;color:#9ea2bb;text-align:center}
    @media print{.card,.section{break-inside:avoid}}
  `;

  const html = `<!doctype html><html><head><meta charset="utf-8"/><title>${esc(orgName)} — Pay Analysis</title><style>${css}</style></head><body>${body}</body></html>`;
  return { html, filename: `${orgName.replace(/\s+/g, "-").toLowerCase()}-pay-analysis.html` };
}
