/**
 * Band-specific factor level definitions — WTW GGS 4.2 §4.2–4.9.
 * Each band evaluates the seven factors against its OWN level set (typically
 * 1–4 levels per factor, not a universal ladder). Extracted from the guide;
 * pages refer to the GGS 4.2 User Guide. Generated data — edit via the source.
 */

import type { FactorId } from "./factors";
import type { BandKey } from "./bands";

export interface BandFactorLevel {
  index: number;
  label: string;
  description: string;
  /** GGS 4.2 User Guide page. */
  page: number;
}

// The CEO band has no factor level definitions in the guide (it is anchored to
// the Company Grade), so it is intentionally absent here.
export const BAND_FACTOR_LEVELS: Partial<Record<BandKey, Record<FactorId, BandFactorLevel[]>>> = {
  "1": {
    functionalKnowledge: [
      { index: 0, label: "Knowledge of a limited number of specific work tasks", description: "Requires no training or previous experience. The tasks are routine, repetitive and manual in nature and specific to the work of the team. The knowledge to perform the job can be obtained within days.", page: 42 },
      { index: 1, label: "Knowledge of activities in own job; focus on (physical) skills gained through training or experience", description: "Technical knowledge required is limited to the tasks performed in own job and is considered basic. The tasks are generally routine and manual. Some formal training or experience is required to perform the job effectively.", page: 42 },
      { index: 2, label: "Full knowledge of activities and procedures of own job", description: "The job requires good understanding of work routines and procedures in own job, which are well defined. The job requires proficient knowledge of these procedures and how to apply them. The knowledge can only be acquired through formal training or considerable experience.", page: 42 },
    ],
    businessExpertise: [
      { index: 0, label: "Little or none other than own job", description: "The job consists of a number of straightforward tasks which require only an understanding of these tasks, thus there is no requirement to understand how the job fits into the business unit or how it interacts with others even within the team.", page: 42 },
      { index: 1, label: "Awareness of how the assigned duties contribute to the work of the team", description: "The job needs to be aware that the tasks relate to the work of others within the immediate team/unit.", page: 42 },
      { index: 2, label: "Good understanding of how the assigned duties contribute to the work of the team", description: "The job requires the understanding of how the assigned duties relate/integrate with the others in the team/unit. Basic knowledge of how the team is organized is needed.", page: 42 },
    ],
    leadership: [
      { index: 0, label: "No supervisory responsibilities", description: "No supervisory responsibility other than self-management of own workload. Should the job have supervisory responsibility of any kind (including mentoring or on-the-job training) it should be graded in a different band.", page: 42 },
    ],
    problemSolving: [
      { index: 0, label: "Uses common sense to complete tasks in straightforward situations", description: "The job needs to possess a basic level of common sense to complete routine tasks. Required to make simple choices of known things, so decision making is limited. Problems that may arise are not sufficiently complex as to require knowledge of technical procedures.", page: 43 },
      { index: 1, label: "Uses simple judgement and defined procedures in straightforward situations", description: "The job is expected to follow detailed and defined rules/instructions and to make simple judgement in straightforward situations, typically having to select from defined and documented alternatives. The job requires a good knowledge and understanding of procedures, and the ability to evaluate and select the correct solution to problems in order to complete the tasks.", page: 43 },
      { index: 2, label: "Selects appropriate alternatives from defined options in a variety of work routines", description: "The job works within well-defined procedures that may involve a variety of work routines. The job needs to understand the procedures and have the capability to evaluate and select the appropriate alternatives from defined options. The job requires the ability to make judgements based on the analysis of factual information.", page: 43 },
    ],
    natureOfImpact: [
      { index: 0, label: "Minimal impact", description: "The job has very limited impact.", page: 43 },
      { index: 1, label: "Indirect impact", description: "The job has an indirect impact on results.", page: 43 },
      { index: 2, label: "Small but direct impact through the accuracy of the tasks performed", description: "The job has limited but direct and measurable impact. Most of the impact is related to the accuracy of the tasks to be executed. Tasks involved are typically very specific and routine (e.g., recording or transaction-related service).", page: 43 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on own job", description: "The impact is primarily restricted to the work of the job only.", page: 43 },
      { index: 1, label: "Primarily on own team", description: "The impact of the job is restricted to their own work team. The quality of the work produced will reflect on the performance and effectiveness of the team as a whole, and the timeliness of the individual's work will reflect on the effectiveness of the team.", page: 43 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Ordinary/common courtesy", description: "The job requires clear verbal communication skills and common courtesy.", page: 43 },
    ],
  },
  "2": {
    functionalKnowledge: [
      { index: 0, label: "Knowledge of activities in own job; focus on (physical) skills gained through training or experience", description: "Technical knowledge required is limited to the tasks performed in own job and is considered basic. The tasks are generally routine and manual. Some training or experience is required to perform the job effectively.", page: 44 },
      { index: 1, label: "Full knowledge of activities and procedures of own job", description: "The job requires good understanding of work routines and procedures in own job, which are well defined. The job requires proficient knowledge of these procedures and how to apply them. The knowledge will typically be acquired through a formal short training program or a familiarization period of several months to develop the appropriate level of experience.", page: 44 },
      { index: 2, label: "Good understanding of procedures and concepts within own discipline", description: "The job requires a good knowledge and comprehensive understanding of the range of processes, procedures and systems to be used in carrying out assigned tasks and a basic understanding of the underlying concepts and principles upon which the job is based. The knowledge can be acquired through a combination of job-related training and considerable on-the-job experience, equivalent to a specialized level within a skilled trade but generally non-theoretical skills.", page: 44 },
    ],
    businessExpertise: [
      { index: 0, label: "Good understanding of how the assigned duties contribute to the work of the team", description: "The job requires the understanding of how the assigned duties relate/integrate with the others in the team/unit. Basic knowledge of how the team is organized is needed.", page: 44 },
      { index: 1, label: "Basic understanding of how the team integrates with others in accomplishing the objectives of the area", description: "The job requires the understanding of how his assigned duties relate with the others in the team/unit, and how the team integrates with others in accomplishing the work of the area/sub-function. Knowledge of the jobs and responsibilities of others in the team is needed to help the job achieve his/her objectives.", page: 44 },
      { index: 2, label: "Good understanding of how the team integrates with others in accomplishing the objectives of the area", description: "The job requires a good understanding of how the team integrates with other teams in order to achieve overall objectives of the area, referring to the way teams co-ordinate their efforts and resources to achieve shared and individual objectives. Where a job has broad responsibilities it will need business acumen that goes beyond the team, and roles involving communication and co-ordination of people and resources across different teams must understand the way these complement and support each other.", page: 44 },
    ],
    leadership: [
      { index: 0, label: "No supervisory responsibilities", description: "No supervisory responsibility.", page: 45 },
      { index: 1, label: "Provides on-the-job training/support to new team members", description: "No supervisory responsibility but is designated to give on-the-job training guidance. On-the-job training refers to training on the specific tasks required to perform the job effectively and the procedures to follow.", page: 45 },
      { index: 2, label: "Allocates work as a team leader; may check on completion/quality", description: "Co-ordinates tasks for the team and may check on quality and work progress. May act as coach/mentor.", page: 45 },
    ],
    problemSolving: [
      { index: 0, label: "Uses simple judgement and defined procedures in straightforward situations", description: "The job is expected to follow detailed and defined rules/instructions and to make simple judgement in straightforward situations, typically having to select from defined and documented alternatives. The job requires a good knowledge and understanding of procedures, and the ability to evaluate and select the correct solution to problems in order to complete the task.", page: 45 },
      { index: 1, label: "Selects appropriate alternatives from defined options in a variety of work routines", description: "The job works within well-defined procedures that may involve a variety of work routines. The job needs to understand the procedures and have the capability to evaluate and select the appropriate alternatives from defined options. The job requires the ability to make judgements based on the analysis of factual information.", page: 45 },
      { index: 2, label: "Uses judgement based on practice and precedence", description: "The job requires the ability to make judgements based on practice and previous experience. This requires the ability to assess the validity and applicability of previous or similar experiences and evaluate options under circumstances that are not covered by procedures.", page: 45 },
    ],
    natureOfImpact: [
      { index: 0, label: "Small but direct impact through the accuracy of the tasks performed", description: "The job has limited but direct and measurable impact. Most of the impact is related to the accuracy of the tasks to be executed. Tasks involved are typically very specific and routine (e.g., recording or transaction-related service).", page: 45 },
      { index: 1, label: "Small but direct impact through the quality of the tasks/service provided by the individual", description: "The job has limited but direct impact by providing services/information on matters that assist others in controlling or making decisions. The work is typically subject to standardized procedures and practices and the impact is related to the quality of execution.", page: 45 },
      { index: 2, label: "Direct impact by ensuring the quality of the task/services/information provided by self and others", description: "The job has a direct impact through their responsibility for the quality of the tasks performed or services provided. The tasks/services involved are closely related to the work of others, thus the quality and timeliness of the service provided and work produced will have an impact on the effectiveness of the team.", page: 45 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on own job", description: "The impact is primarily restricted to the work of the job only.", page: 46 },
      { index: 1, label: "Primarily on own team", description: "The impact of the job is restricted to their own work team. The quality of the work produced will reflect on the performance and effectiveness of the team as a whole, and the timeliness of the individual's work will reflect on the effectiveness of the team.", page: 46 },
      { index: 2, label: "Primarily on closely related work teams", description: "The impact of the job is on their own immediate work team and may also have an impact on closely related work teams whose activities are interdependent (i.e., part of a wider value chain of activities). The performance of the work teams will be influenced by the performance of the individual, with the most immediate impact on their own work team.", page: 46 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Ordinary/common courtesy", description: "The job requires clear verbal communication skills and common courtesy.", page: 46 },
      { index: 1, label: "Involves the regular exchange of information", description: "The job involves the regular exchange of information. There may be occasional handling of awkward contacts. Communication and the exchange of information is an important part of the job.", page: 46 },
      { index: 2, label: "Information exchange requiring tact and diplomacy is a significant feature of the job", description: "The job must be able to exchange ideas and information effectively in a concise and logical way and be sensitive to audience diversity. The job also requires a degree of tact and diplomacy when dealing with others and handling sensitive issues.", page: 46 },
    ],
  },
  "3M": {
    functionalKnowledge: [
      { index: 0, label: "Good understanding of procedures and concepts within own discipline", description: "The job requires a good knowledge and comprehensive understanding of the range of processes, procedures and systems to be used in carrying out assigned tasks and a basic understanding of the underlying concepts and principles upon which the job is based. The knowledge can be acquired through a combination of job-related training and considerable on-the-job experience, equivalent to a specialized level within a skilled trade but generally non-theoretical skills.", page: 47 },
      { index: 1, label: "Good understanding of procedures and concepts within own discipline and a basic knowledge of these elements in other disciplines", description: "The job typically requires a university degree or an extensive amount of practical knowledge gained through experience, and requires an understanding and application of procedures and concepts of own discipline. The requirement for a broader basic knowledge of other concepts and procedures implies the need to understand them in context, how they sit within the business unit as a whole and how they relate to own discipline.", page: 47 },
      { index: 2, label: "In-depth understanding of concepts and principles in own discipline and a basic knowledge of these elements in other disciplines", description: "The job requires professional knowledge gained through substantial applicable work experience, to supplement formal knowledge, in order to apply principles and concepts of own discipline in resolving issues as they arise. Their proficiency enables them to apply and consolidate specialist skills and knowledge, ensure essential procedures are followed, and help to define the standards and specifications around which others will operate.", page: 47 },
    ],
    businessExpertise: [
      { index: 0, label: "Good understanding of how the team integrates with others in accomplishing the objectives of the area", description: "The job requires a good understanding of how the team integrates with other teams in order to achieve overall objectives of the area, referring to the way teams co-ordinate their efforts and resources to achieve shared and individual objectives. Where a job has broad responsibilities it will need business acumen that goes beyond the team, and roles involving communication and co-ordination of people and resources across teams must understand the way these complement and support each other.", page: 47 },
      { index: 1, label: "Basic understanding of how own area integrates within the organization sub-function", description: "The job requires a basic understanding of their own area/team and how it interacts with others within the organization sub-function. The work is closely related to that of other areas to the extent that their performance is subject to their understanding of how areas co-ordinate and contribute to achieving the objectives of the organization sub-function.", page: 47 },
      { index: 2, label: "In-depth understanding of how own area integrates within the organization sub-function and basic commercial awareness", description: "The job requires a comprehensive understanding of how areas collectively integrate within the organization sub-function to contribute to achieving the goals of the business, plus a basic understanding of the industry sector in which it operates. Basic commercial awareness relates to being aware of the competition but with only a superficial understanding of how each competitor differentiates itself and limited understanding of latest developments or changes of market conditions.", page: 47 },
    ],
    leadership: [
      { index: 0, label: "Allocates work as a team leader; may check on completion/quality", description: "Co-ordinates tasks for the team and may check on quality and work progress. May act as coach/mentor.", page: 48 },
      { index: 1, label: "Supervisory responsibilities, leadership of people in all work activities", description: "The job is responsible for providing training for members of the team, monitoring the quantity and quality of the work in progress, coaching employees on performance and contributing to employee pay decisions/changes.", page: 48 },
      { index: 2, label: "Full supervisory responsibilities, contributing to the motivation/development of team through professional leadership", description: "The job has full supervisory responsibility ensuring team members are motivated and capable of delivering a professional service and a high level of performance. Professional leadership includes setting objectives, coaching employees in pursuit of those objectives, appraisal of performance relative to objectives and determination of reward outcomes.", page: 48 },
    ],
    problemSolving: [
      { index: 0, label: "Uses judgement based on practice and precedence", description: "The job requires the ability to make judgements based on practice and previous experience. This requires the ability to assess the validity and applicability of previous or similar experiences and evaluate options under circumstances that are not covered by procedures.", page: 48 },
      { index: 1, label: "Uses judgement based on the analysis of information", description: "The job requires attention to detail in making evaluative judgements based on the analysis of factual information. The job is expected to resolve problems by identifying and selecting solutions through the application of acquired technical experience and will be guided by precedents.", page: 48 },
      { index: 2, label: "Evaluates situations using multiple sources of information", description: "The job requires good analytical skills as well as evaluative judgement based on the analysis of factual and qualitative information in complicated or novel situations. Multiple sources of information refers to a diverse range of internal and external sources, and the complexity relates to the ability to filter, prioritize, analyze and validate potentially complex and dynamic material.", page: 48 },
    ],
    natureOfImpact: [
      { index: 0, label: "Direct impact by ensuring the quality of the task/services/information provided by self and others", description: "The job has a direct impact through their responsibility for the quality of the tasks performed or services provided. The tasks/services involved are closely related to the work of others and thus the quality and timeliness of the service and work produced will have an impact on the effectiveness of the team.", page: 49 },
      { index: 1, label: "Through shared responsibility for volume, quality, timeliness of end results", description: "The job has an impact on the business by influencing decisions through advice, counsel or facilitating services to others, or through joint accountability for the volume, quality and timeliness of end results. The job has no direct responsibility for the financial or resource planning of own area but has some responsibility over the end results.", page: 49 },
      { index: 2, label: "Through responsibility for delivery of end results, and contribution to planning, finances/budget and policy development", description: "The job has an impact through providing value-added perspectives or advisory services important to decision making, or through responsibility for the volume, quality and timeliness of end results. The job also has impact through joint influence over and shared responsibility with more senior management for planning of resources, budgets and policies.", page: 49 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on own team", description: "The impact of the job is restricted to their own work team. The quality of the work produced will reflect on the performance and effectiveness of the team as a whole, and the timeliness of the individual's work will reflect on the effectiveness of the team.", page: 49 },
      { index: 1, label: "Primarily on closely related work teams", description: "The impact of the job is on their own immediate work team and may also have an impact on closely related work teams whose activities are interdependent (i.e., part of a wider value chain of activities). The performance of the work teams will be influenced by the performance of the individual, with the most immediate impact on their own work team.", page: 49 },
      { index: 2, label: "Primarily on an area", description: "The impact of the job is on a work area such that the work and performance of all teams within the area will be directly affected by the performance of the job, which will eventually impact the overall performance and effectiveness of the organization sub-function.", page: 49 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Information exchange requiring tact and diplomacy is a significant feature of the job", description: "The job must be able to exchange ideas and information effectively in a concise and logical way and be sensitive to audience diversity. The job also requires a degree of tact and diplomacy when dealing with others and handling sensitive issues.", page: 50 },
      { index: 1, label: "Developed communication skills to exchange complex information", description: "Sound and comprehensive communication and diplomacy skills are required in order to exchange complex information. Complex information could include sensitive information or information that is difficult to communicate because of its content or its audience.", page: 50 },
      { index: 2, label: "Developed communication and diplomacy skills used to direct/persuade/influence others", description: "Strong communication and diplomacy skills are required to guide, influence and convince others, in particular colleagues in other areas/departments and external customers/agencies.", page: 50 },
    ],
  },
  "4M": {
    functionalKnowledge: [
      { index: 0, label: "In-depth understanding of concepts and principles in own discipline and a basic knowledge of these elements in other disciplines", description: "The job requires professional knowledge gained through substantial applicable work experience, to supplement formal knowledge, in order to apply principles and concepts of own discipline in resolving issues as they arise. Their proficiency enables them to apply and consolidate specialist skills and knowledge, ensure essential procedures are followed, and help to define the standards and specifications around which others will operate.", page: 51 },
      { index: 1, label: "Broad and comprehensive understanding of concepts and principles within own discipline and knowledge of these elements in other disciplines", description: "Job requires a broad and comprehensive understanding of the concepts and principles in their discipline. The requirement for a broader knowledge implies the need to understand other concepts and principles in context in order to resolve issues that have an impact beyond the discipline.", page: 51 },
      { index: 2, label: "Broad and comprehensive understanding of concepts and principles in multiple disciplines", description: "Job requires a broad and comprehensive understanding in multiple disciplines relevant to the business. Managerial positions require an understanding of underlying business principles and the impact of regulatory requirements (where applicable). The job is expected to establish strategic plans and/or operational programs that require a sound understanding of the underlying theories underpinning the disciplines.", page: 51 },
    ],
    businessExpertise: [
      { index: 0, label: "In-depth understanding of how own area integrates within the organization sub-function and basic commercial awareness", description: "The job requires a comprehensive understanding of how areas collectively integrate within the organization sub-function to contribute to achieving the goals of the business, plus a basic understanding of the industry sector in which it operates. Basic commercial awareness relates to being aware of the competition but with only a superficial understanding of how each competitor differentiates itself and limited understanding of latest developments or changes of market conditions.", page: 51 },
      { index: 1, label: "In-depth understanding of how own organization sub-function integrates within the organization function and commercial awareness", description: "The job requires a comprehensive understanding of several organization sub-functions and how their processes and resources interact with other sub-functions to achieve the functional objectives. A good understanding of the industry and commercial awareness is required to understand the relative positioning of the company's products and services versus the competition, along with knowledge of challenges and changes in the sector and how they relate to the company.", page: 51 },
      { index: 2, label: "Broad and comprehensive understanding of concepts and principles in multiple disciplines", description: "The job requires a comprehensive understanding of how all organization sub-functions collectively integrate within the organization function to contribute to achieving the objectives of the business unit. Also required is comprehensive knowledge of the industry in order to contribute to the commercial objectives of the business, including enabling the business unit to differentiate itself from the competition.", page: 51 },
    ],
    leadership: [
      { index: 0, label: "Management responsibilities for team of professionals (includes people, budget and planning)", description: "The job has full management of a team, including management of people, defining roles and responsibilities, planning for the department's future needs and operations, counselling employees on performance and contributing to employee pay decisions/changes.", page: 52 },
      { index: 1, label: "Management responsibility for multiple teams", description: "The job has full management responsibility including the management of numerous teams of managers/professionals, planning for the teams' future needs and operations. There will be financial accountability for independent budgets, and this management-through-managers implies the leadership of a sizeable team of professionals.", page: 52 },
      { index: 2, label: "Management responsibilities for multiple teams doing diverse activities (cross discipline)", description: "The job has full management responsibilities as described above for more than one team involved in various activities, where diverse activities means those outside the core job family, such as management for IT or HR within a Finance role. The job has financial accountability for independent budgets, and the existence of multiple teams implies the part of the business unit managed is co-ordinated by several managers typically with their own independent budgets.", page: 52 },
    ],
    problemSolving: [
      { index: 0, label: "Uses judgement based on the analysis of information", description: "The job requires attention to detail in making evaluative judgements based on the analysis of factual information. The job is expected to resolve problems by identifying and selecting solutions through the application of acquired technical experience and will be guided by precedents.", page: 52 },
      { index: 1, label: "Evaluates situations using multiple sources of information", description: "The job requires good analytical skills as well as evaluative judgement based on the analysis of factual and qualitative information in complicated or novel situations. Multiple sources of information refers to a diverse range of internal and external sources, and the complexity relates to the ability to filter, prioritize, analyze and validate potentially complex and dynamic material.", page: 52 },
      { index: 2, label: "Requires complex judgement based on advanced analytical thought", description: "The job covers a wide range of activities that require complex judgements and solutions based on sophisticated analytical thought comparing and selecting complex alternatives. In-depth analysis with interpretative thinking will be required to define problems and develop innovative solutions, and extensive research is usually called for although it may not be conducted or even championed by the individual.", page: 52 },
    ],
    natureOfImpact: [
      { index: 0, label: "Through responsibility for delivery of end results, and contribution to planning, finances/budget and policy development", description: "The job has an impact through providing value-added perspectives or advisory services important to decision making, or through responsibility for the volume, quality and timeliness of end results. The job also has impact through joint influence over and shared responsibility with more senior management for planning of resources, budgets and policies.", page: 53 },
      { index: 1, label: "Through responsibility for planning, finances/budget, end results and setting policies", description: "The job has an impact by exercising control over resources, policy formulation and planning. The job has primary accountability for the end results.", page: 53 },
      { index: 2, label: "Through contribution to strategic decisions", description: "The job has an impact by exercising control over sizeable resources, policy formulating and planning of the function. The role has a significant influence over the future strategy.", page: 53 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on an area", description: "The impact of the job is on a work area such that the work and performance of all teams within the area will be directly affected by the performance of the job, which will eventually impact the overall performance and effectiveness of the organization sub-function.", page: 53 },
      { index: 1, label: "Primarily on an organization sub-function", description: "The impact of the job is on an organization sub-function. A sizeable impact implies the job is either managing the sub-function or belongs to it and has a big impact in terms of size (people, revenue, budget) of team managed, strategic influence on the sub-function, and interaction with other teams of the same function such that their performance severely affects other sub-functions' performance.", page: 53 },
      { index: 2, label: "Primarily on an organization function", description: "The job has a sizeable impact on an entire organization function. A sizeable impact implies the job is either managing the function or belongs to it and has a big impact in terms of size (people, revenue, budget) of team managed, strategic influence on the function, and interaction with other functions such that their performance severely affects other functions' performance.", page: 53 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Developed communication and diplomacy skills used to direct/persuade/influence others", description: "Strong communication and diplomacy skills are required to guide, influence and convince others, in particular colleagues in other areas/departments and external customers/agencies.", page: 54 },
      { index: 1, label: "Developed communication skills, ability to negotiate mainly internally and often at higher levels", description: "The job needs a very high level of communication skills, including interactive listening, in order to negotiate (mainly internally) with others often at a senior level. Jobs with managerial responsibilities for a large or complex team of professionals requiring special communication skills function at this level, and some external communication is required although it is not the primary focus.", page: 54 },
      { index: 2, label: "Developed communication skills to negotiate internally and externally at high levels", description: "The job requires developed communication skills and the ability to negotiate with a high level of discretion (internally and externally) with others often at a senior level. The negotiations will have an impact on the business unit and are likely to involve both internal and external parties such as clients, government bodies and other organizations.", page: 54 },
    ],
  },
  "5FS": {
    functionalKnowledge: [
      { index: 0, label: "Broad and comprehensive understanding of theories and practices in a discipline", description: "The job requires a broad and comprehensive understanding of the different systems, theories and practices relevant to a discipline. The knowledge will not have to be in-depth as the focus of the job is on the managerial rather than the technical aspects within their discipline.", page: 55 },
      { index: 1, label: "Broad and comprehensive understanding of theories and practices in multiple disciplines or a fast-changing discipline", description: "The job requires a broad and comprehensive understanding of the different systems, theories and practices relevant to multiple disciplines or a fast-changing discipline. The need to understand multiple disciplines focuses on the knowledge requirements to manage heterogeneous workforces with multiple stakeholders in line with broader strategic considerations, and fast-changing refers to the fundamental knowledge of the discipline itself rather than the business environment.", page: 55 },
      { index: 2, label: "Broad and comprehensive understanding of theories and practices in a theory-based (scientific) discipline", description: "The job requires a broad and comprehensive understanding of different systems, theories and practices relevant to a theory-based discipline. The role must keep abreast of new developments and innovations often supported by complex theories, ground-breaking hypotheses or research rather than by traditional, fully accepted standards and methods.", page: 55 },
    ],
    businessExpertise: [
      { index: 0, label: "In-depth understanding of how own organization sub-function integrates within the organization function and commercial awareness", description: "The job requires a comprehensive understanding of several organization sub-functions and how their processes and resources interact with other sub-functions to achieve the functional objectives. A good understanding of the industry and commercial awareness is required to understand the relative positioning of the company's products and services versus the competition, plus knowledge of challenges and changes in the sector and how they relate to the company.", page: 55 },
      { index: 1, label: "In-depth knowledge of how own organization function integrates within the business unit and of direct competitors (products/services)", description: "The job requires a comprehensive understanding of how all organization sub-functions collectively integrate within the organization function to contribute to achieving the objectives of the business unit. Also required is comprehensive knowledge of the industry in order to contribute to the commercial objectives of the business, including enabling the business unit to differentiate itself from the competition.", page: 55 },
      { index: 2, label: "In-depth knowledge of multiple organization functions' contributions to achieving business objectives and of industry/direct competitors' strategies", description: "The job requires a comprehensive understanding of a significant part of the business unit (how organization functions operate, integrate, set targets and co-ordinate their efforts) together with knowledge of the industry in which the company operates, including an understanding of economic, commercial and political issues affecting the industry.", page: 55 },
    ],
    leadership: [
      { index: 0, label: "Management responsibility for a team of professionals", description: "The job has full management responsibility including the management of a team of professionals, planning for the team's future needs and operations. There will be financial accountability for an independent budget.", page: 56 },
      { index: 1, label: "Management responsibility through subordinate managers", description: "The job has full management responsibility including the management of numerous teams of managers/professionals, planning for the teams' future needs and operations. There will be financial accountability for independent budgets, and this management-through-managers implies the leadership of a sizeable team of professionals.", page: 56 },
      { index: 2, label: "Management responsibility through subordinate managers performing diverse activities", description: "The job has full management responsibility including the management of numerous teams of managers/professionals across the spectrum of different activities within a major function, planning for the teams' future needs and operations. There will be financial accountability for independent budgets.", page: 56 },
    ],
    problemSolving: [
      { index: 0, label: "Requires complex judgement based on advanced analytical thought", description: "The job covers a wide range of activities that require complex judgements and solutions based on sophisticated analytical thought comparing and selecting complex alternatives. In-depth analysis with interpretative thinking will be required to define problems and develop innovative solutions, and extensive research is usually called for although it may not be conducted or even championed by the individual.", page: 56 },
      { index: 1, label: "Leads the development of innovative solutions and/or is required to deliver the solutions in a fast-changing environment", description: "The job is typically expected to direct/lead the development of solutions that go beyond existing precedents, assumptions or current knowledge of sophisticated disciplines and business challenges. Solutions are expected to be innovative and designed to lead the organization function (or even business unit) into new directions, markets, channels or customer bases, and a particular challenge may be leading this development in a fast-changing environment where long-term planning may be difficult.", page: 56 },
      { index: 2, label: "Requires conceptual thinking in complex/completely new situations", description: "The job covers a wide range of activities requiring advanced judgement to develop new solutions. Conclusions are typically drawn through a consequence of sequential analysis based on extensive research that will typically be championed by the job, and the use of ground-breaking/very innovative methods is an important part of the role.", page: 56 },
    ],
    natureOfImpact: [
      { index: 0, label: "As part of a support organization function", description: "An organization function is considered support if it facilitates the work done by other functions by providing support/infrastructure to produce an impact on the business, and its performance may not be clearly measured by business performance indicators as there is an indirect relationship.", page: 57 },
      { index: 1, label: "As part of a key organization function", description: "An organization function is considered key if the work delivered is part of the core business process (delivering the core business service or product(s), typically generating revenue), or if the work is not part of the core process but has a direct influence such that changes in its performance have a sizeable impact on the end results of the business unit.", page: 57 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on part of an organization function", description: "The job has a sizeable impact on part of an organization function. A sizeable impact implies the job is either managing an important part of the function or has a major impact in terms of size (people, revenue, budget) of team managed, strategic influence on the function, and interaction with other areas of the same function such that their performance severely affects other teams' performance.", page: 57 },
      { index: 1, label: "Primarily on an organization function", description: "The job has a sizeable impact on an entire organization function. A sizeable impact implies the job is either managing the function or belongs to it and has a big impact in terms of size (people, revenue, budget) of team managed, strategic influence on the function, and interaction with other functions such that their performance severely affects other teams' performance.", page: 57 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Communication skills required to manage team of professionals", description: "The job requires developed communication skills and the ability to negotiate and influence within their team with a high level of discretion. The job needs to be an empathetic communicator to effectively manage their team and resources.", page: 58 },
      { index: 1, label: "High level of sensitivity to audience to modify the beliefs/opinions", description: "The job will have sound communication skills to enable them to modify the beliefs and opinions of their teams and other peers in the business unit. Establishing effective collaborative relations with other departments within the business unit or external organizations is a critical part of the job, and the ability to do this successfully will greatly impact the job's overall effectiveness.", page: 58 },
      { index: 2, label: "Skilled communicator who influences and negotiates with great latitude on outcomes", description: "The job will be a convincing and persuasive communicator who can influence a wide range of audiences and may represent a major function in external events. The focus will be to present and defend complicated or delicate issues that will have an important impact on the business, and the job is likely to be involved in both internal and external negotiations with a major impact on the function and possibly the entire business unit.", page: 58 },
    ],
  },
  "5BS": {
    functionalKnowledge: [
      { index: 0, label: "Broad and comprehensive understanding of theories and practices in a discipline", description: "The job requires a broad and comprehensive understanding of the different systems, theories and practices relevant to a discipline. The knowledge will not have to be in-depth as the focus of the job is on the managerial rather than the technical aspects within their discipline.", page: 59 },
      { index: 1, label: "Broad and comprehensive understanding of theories and practices in multiple disciplines or a fast-changing discipline", description: "The job requires a broad and comprehensive understanding of the different systems, theories and practices relevant to multiple disciplines or a fast-changing discipline. The need to understand multiple disciplines focuses on the knowledge requirements to manage heterogeneous workforces with multiple stakeholders in line with broader strategic considerations, and fast-changing refers to the fundamental knowledge of the discipline itself rather than the business environment.", page: 59 },
      { index: 2, label: "Broad and comprehensive understanding of theories and practices in a theory-based (scientific) discipline", description: "The job requires a broad and comprehensive understanding of different systems, theories and practices relevant to a theory-based discipline. The role must keep abreast of new developments and innovations often supported by complex theories, ground-breaking hypotheses or research rather than by traditional, fully accepted standards and methods.", page: 59 },
    ],
    businessExpertise: [
      { index: 0, label: "In-depth knowledge of how own organization function integrates within the business unit and of direct competitors (products and services)", description: "The job requires a comprehensive understanding of how all organization sub-functions collectively integrate within the organization function to contribute to achieving the objectives of the business unit. Also required is comprehensive knowledge of the industry in order to contribute to the commercial objectives of the business, including enabling the business unit to differentiate itself from the competition.", page: 59 },
      { index: 1, label: "In-depth knowledge of multiple organization functions' contributions to achieving business objectives and of industry/direct competitors' strategies", description: "The job requires a comprehensive understanding of a significant part of the business unit (how functions operate, integrate, set targets and co-ordinate their efforts) together with knowledge of the industry in which the company operates, including an understanding of economic, commercial and political issues affecting the industry.", page: 59 },
      { index: 2, label: "Understanding of total business unit and in-depth knowledge of industry and commercial environment", description: "The job requires a comprehensive understanding of the total business unit (how all functions operate, integrate, set targets and co-ordinate their efforts) together with an in-depth knowledge of the industry in which the company operates, including a thorough understanding of economic, commercial and political issues affecting the industry.", page: 59 },
    ],
    leadership: [
      { index: 0, label: "Management responsibility for a team of professionals", description: "The job has full management responsibility including the management of a team of professionals, planning for the team's future needs and operations. There will be financial accountability for an independent budget.", page: 60 },
      { index: 1, label: "Management responsibility through subordinate managers", description: "The job has full management responsibility including the management of numerous teams of managers/professionals, planning for the teams' future needs and operations, with financial accountability for independent budgets. This management-through-managers implies the leadership of a sizeable team of professionals.", page: 60 },
      { index: 2, label: "Management responsibilities for very diverse activities within a major part of the business unit, through subordinate managers", description: "The job has full management responsibility including the management of numerous teams of managers/professionals performing very diverse activities for a major part of the business unit, planning for the teams' future needs and operations. There will be financial accountability for independent budgets.", page: 60 },
    ],
    problemSolving: [
      { index: 0, label: "Requires complex judgement based on advanced analytical thought", description: "The job covers a wide range of activities that require complex judgements and solutions based on sophisticated analytical thought comparing and selecting complex alternatives. In-depth analysis with interpretative thinking will be required to define problems and develop innovative solutions, and extensive research is usually called for although it may not be conducted or even championed by the individual.", page: 60 },
      { index: 1, label: "Leads the development of innovative solutions and/or is required to deliver the solutions in a fast-changing environment", description: "The job is typically expected to direct/lead the development of solutions that go beyond existing precedents, assumptions or current knowledge of sophisticated disciplines and business challenges. Solutions are expected to be innovative and designed to lead the organization function (or even business unit) into new directions, markets, channels or customer bases, and a particular challenge may be leading this development in a fast-changing environment where long-term planning may be difficult.", page: 60 },
      { index: 2, label: "Requires conceptual thinking in complex/completely new situations", description: "The job covers a wide range of activities requiring advanced judgement to develop new solutions. Conclusions are typically drawn through a consequence of sequential analysis based on extensive research that will typically be championed by the job, and the use of ground-breaking/very innovative methods is an important part of the role.", page: 60 },
    ],
    natureOfImpact: [
      { index: 0, label: "Through responsibility for a support organization function", description: "An organization function is considered support if it facilitates the work done by other functions by providing support/infrastructure to produce an impact on the business, and its performance may not be clearly measured by business performance indicators as there is an indirect relationship.", page: 61 },
      { index: 1, label: "Through responsibility for a key organization function", description: "An organization function is considered key if the work delivered is part of the core business process (delivering the core business service or product(s), typically generating revenue), or if the work is not part of the core process but has a direct influence such that changes in its performance have a sizeable impact on the end results of the business unit.", page: 61 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on an organization function", description: "The job has a sizeable impact on an entire organization function. A sizeable impact implies the job is either managing the function or belongs to it and has a big impact in terms of size (people, revenue, budget) of team managed, strategic influence on the function, and interaction with other functions such that their performance severely affects other teams' performance.", page: 61 },
      { index: 1, label: "Primarily on the entire business unit as a member of the executive leadership team", description: "A job with a sizeable impact on a business unit will either manage a major organization function (or number of functions) or be part of the senior leadership team of the business unit with a place on the key decision-making body of that unit.", page: 61 },
    ],
    interpersonalSkills: [
      { index: 0, label: "High level of sensitivity to audience to modify the beliefs/opinions", description: "The job will have sound communication skills to enable them to modify the beliefs and opinions of their teams and other peers in the business unit. Establishing effective collaborative relations with other departments within the business unit or external organizations is a critical part of the job, and the ability to do this successfully will greatly impact the job's overall effectiveness.", page: 62 },
      { index: 1, label: "Skilled communicator who influences and negotiates with great latitude on outcomes", description: "The job will be a convincing and persuasive communicator who can influence a wide range of audiences and may represent a major function in external events. The focus will be to present and defend complicated or delicate issues that will have an important impact on the business, and the job is likely to be involved in both internal and external negotiations with a major impact on the function and possibly the entire business unit.", page: 62 },
      { index: 2, label: "Skilled communicator who influences and shapes the image of the business unit (perhaps the industry)", description: "The job represents the company at external events and must have highly developed communication skills to shape the image of the company. The focus of the job will be to present and defend complicated or delicate issues that will have an important impact on the business unit.", page: 62 },
    ],
  },
  "3IC": {
    functionalKnowledge: [
      { index: 0, label: "Good understanding of procedures and concepts within own discipline", description: "The job requires a good knowledge and comprehensive understanding of the range of processes, procedures and systems to be used in carrying out assigned tasks and a basic understanding of the underlying concepts and principles upon which the job is based. The knowledge can be acquired through a combination of job-related training and considerable on-the-job experience, equivalent to a specialized level within a skilled trade but generally non-theoretical skills.", page: 63 },
      { index: 1, label: "Good understanding of procedures and concepts within own discipline and a basic knowledge of these elements in other disciplines", description: "The job typically requires a university degree or an extensive amount of practical knowledge gained through experience, and requires an understanding and application of procedures and concepts of own discipline. The requirement for a broader basic knowledge of other concepts and procedures implies the need to understand them in context, how they sit within the business unit as a whole and how they relate to own discipline.", page: 63 },
      { index: 2, label: "In-depth understanding of concepts and principles in own discipline and a basic knowledge of these elements in other disciplines", description: "The job requires professional knowledge gained through substantial applicable work experience, to supplement formal knowledge, in order to apply principles and concepts of own discipline in resolving issues as they arise. Their proficiency enables them to apply and consolidate specialist skills and knowledge, ensure essential procedures are followed, and help to define the standards and specifications around which others will operate.", page: 63 },
    ],
    businessExpertise: [
      { index: 0, label: "Good understanding of how the team integrates with others in accomplishing the objectives of the area", description: "The job requires a good understanding of how the team integrates with other teams in order to achieve overall objectives of the area, referring to the way teams co-ordinate their efforts and resources to achieve shared and individual objectives. Where a job has broad responsibilities it will need business acumen that goes beyond the team, and roles involving communication and co-ordination of people and resources across teams must understand the way these complement and support each other.", page: 63 },
      { index: 1, label: "Basic understanding of how own area integrates within the organization sub-function", description: "The job requires a basic understanding of their own area/team and how it interacts with others within the organization sub-function. The work is closely related to that of other areas to the extent that their performance is subject to their understanding of how areas co-ordinate and contribute to achieving the objectives of the organization sub-function.", page: 63 },
      { index: 2, label: "In-depth understanding of how own area integrates within the organization sub-function and basic commercial awareness", description: "The job requires a comprehensive understanding of how areas collectively integrate within the organization sub-function to contribute to achieving the goals of the business, plus a basic understanding of the industry sector in which it operates. Basic commercial awareness relates to being aware of the competition but with only a superficial understanding of how each competitor differentiates itself and limited understanding of latest developments or changes of market conditions.", page: 63 },
    ],
    leadership: [
      { index: 0, label: "No supervisory responsibility", description: "No supervisory responsibility.", page: 64 },
      { index: 1, label: "Provides on-the-job training/support to new team members", description: "No supervisory responsibility but provides informal guidance and support to new team members. On-the-job training refers to training on the specific tasks required to perform the job effectively and the procedures to follow.", page: 64 },
      { index: 2, label: "Mentors junior team members", description: "The job will act as an advisor and coach to mentor junior members of the team.", page: 64 },
      { index: 3, label: "Allocates/co-ordinates work within the team/project and/or contributes to technical/professional direction for a discipline", description: "The job is responsible for handling day-to-day staff management issues, including resource management and allocation of work. In a purely technical/professional role, the job has an advisory role and/or influence over the direction of a discipline that is key to the business unit, and the decisions it influences or advises on will contribute to determining technical/professional developments.", page: 64 },
    ],
    problemSolving: [
      { index: 0, label: "Uses judgement based on practice and precedence", description: "The job requires the ability to make judgements based on practice and previous experience. This requires the ability to assess the validity and applicability of previous or similar experiences and evaluate options under circumstances that are not covered by procedures.", page: 64 },
      { index: 1, label: "Uses judgement based on the analysis of information", description: "The job requires attention to detail in making evaluative judgements based on the analysis of factual information. The job is expected to resolve problems by identifying and selecting solutions through the application of acquired technical experience and will be guided by precedents.", page: 64 },
      { index: 2, label: "Evaluates situations using multiple sources of information", description: "The job requires good analytical skills as well as evaluative judgement based on the analysis of factual and qualitative information in complicated or novel situations. Multiple sources of information refers to a diverse range of internal and external sources, and the complexity relates to the ability to filter, prioritize, analyze and validate potentially complex and dynamic material.", page: 64 },
    ],
    natureOfImpact: [
      { index: 0, label: "Small but direct impact through the quality of the tasks/service provided by the individual", description: "The job has limited but direct impact by providing services/information on matters that assist others in controlling or making decisions. The work is typically subject to standardized procedures and practices and the impact is related to the quality of execution.", page: 65 },
      { index: 1, label: "Direct impact by ensuring the quality of the task/services/information provided by self and others", description: "The job has a direct impact through their responsibility for the quality of the tasks performed or services provided. The tasks/services involved are closely related to the work of others and thus the quality and timeliness of the service and work produced will have an impact on the effectiveness of the team.", page: 65 },
      { index: 2, label: "Inputs to decisions within own discipline", description: "The job has an impact by influencing decisions through advice, counsel or facilitating services to others in area of specialization.", page: 65 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on own team", description: "The impact of the job is restricted to their own work team. The quality of the work produced will reflect on the performance and effectiveness of the team as a whole, and the timeliness of the individual's work will reflect on the effectiveness of the team.", page: 65 },
      { index: 1, label: "Primarily on closely related work teams", description: "The impact of the job is on their own immediate work team and may also have an impact on closely related work teams whose activities are interdependent (i.e., part of a wider value chain of activities). The performance of the work teams will be influenced by the performance of the individual, with the most immediate impact on their own work team.", page: 65 },
      { index: 2, label: "Primarily on an area", description: "The impact of the job is on a work area such that the work and performance of all teams within the area will be directly affected by the performance of the job, which will eventually impact the overall performance and effectiveness of the organization sub-function.", page: 65 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Information exchange requiring tact and diplomacy is a significant feature of the job", description: "The job must be able to exchange ideas and information effectively in a concise and logical way and be sensitive to audience diversity. The job also requires a degree of tact and diplomacy when dealing with others and handling sensitive issues.", page: 66 },
      { index: 1, label: "Developed communication skills to exchange complex information", description: "Sound and comprehensive communication and diplomacy skills are required in order to exchange complex information. Complex information could include sensitive information or information that is difficult to communicate because of its content or its audience.", page: 66 },
      { index: 2, label: "Developed communication and diplomacy skills used to direct/persuade/influence others", description: "Strong communication and diplomacy skills are required to guide, influence and convince others, in particular colleagues in other areas/departments and external customers/agencies.", page: 66 },
    ],
  },
  "4IC": {
    functionalKnowledge: [
      { index: 0, label: "Specialist in a discipline", description: "The role requires expertise within a discipline in a specialized field, and there are typically multiple people within the business unit who provide the same level of subject matter expertise, tending to be divided along product, service or geographic lines. The job provides technical guidance and direction for his/her area of specialization.", page: 67 },
      { index: 1, label: "Expert in a discipline", description: "As a key expert, the job requires in-depth knowledge and understanding within one discipline and is regarded within the business unit as a technical expert in their particular field. It is a requirement that the role is an acknowledged authority both within and outside his/her area of expertise, and there is typically a small number of people in the business unit who provide the same level of subject matter expertise.", page: 67 },
      { index: 2, label: "'Guru'/internal/external recognized expert in discipline that is key to the business unit", description: "The job requires a broad and comprehensive understanding of the field and is considered a guru, recognized for their technical expertise maybe even beyond the business unit itself. The role is a recognized resource for innovation or ground-breaking developments.", page: 67 },
    ],
    businessExpertise: [
      { index: 0, label: "In-depth understanding of how own discipline integrates with the organization function and basic commercial awareness", description: "The job requires a comprehensive understanding of how areas collectively integrate within the organization sub-function to contribute to achieving the goals of the business, plus a basic understanding of the industry sector in which it operates. Basic commercial awareness relates to being aware of the competition but with only a superficial understanding of how each competitor differentiates itself and limited understanding of latest developments or changes of market conditions.", page: 67 },
      { index: 1, label: "Good knowledge of how own discipline contributes to the business unit and good understanding of competitors (products/services)", description: "The job requires a good knowledge of how it contributes to the goals in the business unit, requiring comprehensive knowledge of several areas within a function and how their processes and resources interact with other areas to achieve the organization functional objectives. A good understanding of the industry is also necessary along with knowledge of how the competition aims to differentiate itself.", page: 67 },
      { index: 2, label: "In-depth knowledge of how own discipline contributes to the business unit and good understanding of the commercial environment/market", description: "The job requires a comprehensive understanding of how it contributes to achieving the objectives of the business unit. Also required is a very good working knowledge of the industry in order to contribute to the commercial objectives of the business unit.", page: 67 },
    ],
    leadership: [
      { index: 0, label: "No supervisory responsibility or may mentor junior team members", description: "No supervisory responsibility but the job may act as an advisor and coach to mentor junior members of the team.", page: 68 },
      { index: 1, label: "Allocates/co-ordinates work within the team/project and/or contributes to technical/professional direction for a discipline", description: "The job is responsible for handling day-to-day staff management issues, including resource management and allocation of work. In a purely technical/professional role, the job has an advisory role and/or influence over the direction of a discipline that is key to the business unit, and the decisions it influences or advises on will contribute to determining technical/professional developments.", page: 68 },
      { index: 2, label: "Thought leadership in a discipline that is key to the business unit", description: "The job has responsibility for setting the technical/professional direction of an area of expertise that is key to the business unit. The decisions made at this level will determine technical/professional developments and the strategy for the discipline.", page: 68 },
    ],
    problemSolving: [
      { index: 0, label: "Evaluates situations using multiple sources of information", description: "The job requires good analytical skills as well as evaluative judgement based on the analysis of factual and qualitative information in complicated or novel situations. Multiple sources of information refers to a diverse range of internal and external sources, and the complexity relates to the ability to filter, prioritize, analyze and validate potentially complex and dynamic material.", page: 68 },
      { index: 1, label: "Requires complex judgement based on advanced analytical thought", description: "The job covers a wide range of activities that require complex judgements and solutions based on sophisticated analytical thought comparing and selecting complex alternatives. In-depth analysis with interpretative thinking will be required to define problems and develop innovative solutions, and extensive research is usually called for although it may not be conducted or even championed by the individual.", page: 68 },
      { index: 2, label: "Requires conceptual and innovative thinking to develop ground-breaking solutions", description: "The job covers a wide range of activities requiring advanced judgement to develop new solutions, with conclusions typically drawn through a consequence of sequential analysis based on extensive research championed by the job. The job is typically required to think beyond existing solutions, assumptions or current knowledge of sophisticated areas, and the use of ground-breaking/very innovative methods is an important part of the role.", page: 68 },
    ],
    natureOfImpact: [
      { index: 0, label: "Inputs to decisions within own discipline", description: "The job has an impact by influencing decisions through advice, counsel or facilitating services to others in area of specialization.", page: 69 },
      { index: 1, label: "Inputs to strategy within own discipline", description: "The job has an impact on the business through contribution to professional/technical direction and strategic decisions for the area of specialty. This contribution necessitates a degree of responsibility over the professional/technical strategy, and jobs that only provide some help should be graded on the first level for this factor.", page: 69 },
      { index: 2, label: "By setting strategy within own discipline", description: "The job has an impact on the business through making decisions that determine professional/technical approaches and strategies for the area of specialty. The job will be ultimately responsible for the strategic direction of a professional/technical area.", page: 69 },
    ],
    areaOfImpact: [
      { index: 0, label: "Primarily on an area", description: "The impact of the job is on a work area such that the work and performance of all teams within the area will be directly affected by the performance of the job, which will eventually impact the overall performance and effectiveness of the organization sub-function.", page: 69 },
      { index: 1, label: "Primarily on an organization sub-function", description: "The impact of the job is on an organization sub-function. A sizeable impact implies the job is either managing the sub-function or belongs to it and has a big impact in terms of strategic influence on the sub-function and interaction with other teams of the same function such that their performance severely affects other sub-functions' performance.", page: 69 },
      { index: 2, label: "Primarily on an organization function", description: "The job has a sizeable impact on an entire organization function. A sizeable impact implies the job is either managing the function or belongs to it and has a big impact in terms of strategic influence on the function and interaction with other functions such that their performance severely affects other teams' performance.", page: 69 },
    ],
    interpersonalSkills: [
      { index: 0, label: "Developed communication and diplomacy skills used to direct/persuade/influence others", description: "Strong communication and diplomacy skills are required to guide, influence and convince others, in particular colleagues in other areas/departments and external customers/agencies.", page: 70 },
      { index: 1, label: "Developed communication skills, ability to negotiate mainly internally and often at higher levels", description: "The job needs a very high level of communication skills, including interactive listening, in order to negotiate (mainly internally) with others often at a senior level. Jobs with managerial responsibilities for a large or complex team of professionals requiring special communication skills function at this level, and some external communication is required although it is not the primary focus.", page: 70 },
      { index: 2, label: "Developed communication skills to negotiate internally and externally at high levels", description: "The job requires developed communication skills and the ability to negotiate with a high level of discretion (internally and externally) with others often at a senior level. The negotiations will have an impact on the business unit and are likely to involve both internal and external parties such as clients, government bodies and other organizations.", page: 70 },
    ],
  },
};

export function factorLevels(band: BandKey, factorId: FactorId): BandFactorLevel[] {
  return BAND_FACTOR_LEVELS[band]?.[factorId] ?? [];
}
